### ISSUE TITLE
Show Error:_ReactNativeMaterialKit.mdl.progress.indeterminateProgress() undefiend

### ISSUE THREAD

**Issue by llgoer** [TeletronicsDotAe/ReactMessenger#1]
After I git clone this project,than run 'npm install&&rnpm link'.
When I run in both IOS and Android System.
Show Error Like'_ReactNativeMaterialKit.mdl.progress.indeterminateProgress() is undefiend'.

**Comment by Froelund** [comment]
Thanks for the feedback @yanghuxiao . I will take a look at it.

**Comment by Froelund** [comment]
Hey @yanghuxiao 
Fixed. Please pull the repository and try again.

**Comment by llgoer** [comment]
thanks
